version: "3"
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app:delegated
    environment:
      XDEBUG_CONFIG: "remote_enable=1 remote_host=hostmachine idekey=command-dispatcher profiler_enable=0"
    extra_hosts:
      - "hostmachine:172.17.0.1"
    command: tail -f /dev/null