version: "3"
services:
  php74:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app:delegated
    environment:
      XDEBUG_CONFIG: "remote_enable=1 remote_host=host.docker.internal idekey=metamorphosis profiler_enable=0"
    command: tail -f /dev/null
  php80:
    image: php:8.0-fpm-alpine3.15
    volumes:
      - ./:/app:delegated
    working_dir: /app
    command: tail -f /dev/null
  php81:
    image: php:8.1-alpine3.14
    volumes:
      - ./:/app:delegated
    working_dir: /app
    command: tail -f /dev/null